travis:
  secure:
    BINSTAR_TOKEN: FHAP1stbs/WCuXAxnvRU0kvQOOPkHsW94YsDbeSUvg6TV9bgKfTwlojJjLjNXB4wBw9K+LySISAkIO3y3DGfCjbhhsE5XRUJNecF9JHXfuYkWoiqS4rFPfY/sWQwmOOxIkJHGwh2P3sGwzDkJuAeLOMLkBjSnnDw5TWwZ8s59DwFmKEvDKdZhR3FZ46RagEUqdCb0TBs7lk10kZHZI7eKhPXbYlsZPIUxPJI/j6FIQi7ms31L5sfXEhUXJl2AUiQH24PIrLycBPES3Tf4W00xDftS3+XFa/VlPbsvYOeLHru6RbQ0BTjX4+KcWl1zcWWnFoV75cGSNUwIwcS2tCg7OaEwoZg0CCdSyLRop2SFutKWy0+pG2VxXNfQgRv5p1GO44Go99dGF9joqDomN0Glv6c4/g4+mxeJA1/qCVPYUGPdOICpO0t6tUpMDR6wLvnJS+cS+GyrQd6hR7TzxWZWqWTOXNSiMEjiL13+0V11SzRDtkZCVnZ5yXvg4ckrh9CNasi/ElM7tqNvgKzSlsewHAiSqTfNGe9hxutYY6nKYNNp37WeBt+MmTlZDU/6WC8VWcjuFsU+th5TGyMshFF7dnr1tjnMjyx8dUjL+CozNE0YAl1VUMTHRgP/S6ryUVOc+PD3ivhrfrxEcoOfFECnldqQp4ayc9I4lj7bC29F1M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
