travis:
  secure:
    BINSTAR_TOKEN: e45wEpRCIrHMV6/jg0tfmWwH9KXZCU8mnIt1e+YEvb+7wKJqj1hw9XdePh2Uq7+VqyIE4cvUs/wxDQbfbQpUJYSboqusP0W1gzQxDIxOpd6xeSg9a+zYbOaBxdsc1X+oUMVxfTU8VjR8t4hmrspg0oTvHn4Be/oqI3AQPc1oaljb50auhr8na+PvMzxV0s8UK3r0tBV/4Bho5LEK2Cy8K12kMt9XxJFC/FMxq4EWuKyO9s5TYMWB1Gty5A7D9fdAHFRTE+hRRGt6Sg22osTMuPDrGLSLFgxlb4fKtcfbVwgoO0MUpOoxc3KTWrbxhFlEH9GnQQKGUxl9tPMb8x5wjNoRV3p5H1rBixTQJiaTu/CQyvLc+CO+km+W6RmxOuodqFzL0COUAiJ14DVbzwMZGrK24et2kYiwKBVa9GcJ382FspqV5d+e78eT79JlrEEIn95i+3FAUomyZcwSJtQOjmH44zZhvK9xJsKPbor7/B6MfVKpPnsAGpzWGJTYgbrbaxsE7fsgd4XkY4RFgV/GMRHBDBYhTepW/YeLgyjjUWOItTr7FDWcv16h5g8w8gkpHXcmkNuq7diKJleFUNSZEMdjFRu5yVmir2QrCGqDnVqnkIVZM+bXBIotqYs4Nc8CbLms87eLHTSjaMVJRa90CnVKc51Wl/cO0emrtK5Y7Fs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
